#!/usr/bin/env python3
"""Post-production pass: stitch a variant's clips into the finished ad.

  python3 pipeline/superscale.py check                    # is the API configured?
  python3 pipeline/superscale.py push out/<slug>/manifest.json [--only <variant>]

Superscale's REST surface is not public, so this ships disabled. Two ways to use it:

  1. Fill in base_url + paths + api_key_env for superscale in providers.json and
     set "enabled": true. Each variant is then submitted as one job carrying the
     rendered clip urls and the copy from the pack.
  2. Leave it disabled. Every variant still gets a hand-off file
     (prompts/<variant>/superscale.json) to drop into the Superscale UI, plus a
     generated assemble.sh that concatenates the clips locally with ffmpeg, so a
     brief still ends as a watchable cut without any second vendor.
"""

import json
import shlex
import time
from pathlib import Path

from common import (
    PipelineError,
    State,
    classify,
    die,
    dig,
    download,
    find_media_urls,
    headers_for,
    load_config,
    load_env_file,
    log,
    request_json,
    run_cli,
)

PROVIDER = "superscale"


def variants_from(manifest):
    """Group manifest jobs back into variants, in scene order."""
    grouped = {}
    for job in manifest["jobs"]:
        grouped.setdefault(job["variant"], []).append(job)
    for jobs in grouped.values():
        jobs.sort(key=lambda j: j["scene"])
    return grouped


def clip_urls(state, jobs):
    """Rendered asset urls, or None if any clip of the variant is not done yet."""
    urls = []
    for job in jobs:
        entry = state.get(job["job_id"])
        if entry.get("status") != "done" or not entry.get("url"):
            return None
        urls.append(entry["url"])
    return urls


def write_assemble_script(out_dir, grouped, state):
    """Local fallback cut: concat the clips of each variant with ffmpeg."""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by pipeline/superscale.py - local assembly fallback.",
        "# Concatenates each variant's rendered clips into one file under final/.",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "command -v ffmpeg >/dev/null || { echo 'ffmpeg is not installed' >&2; exit 1; }",
        "mkdir -p final",
        "",
    ]
    written = 0
    for variant, jobs in grouped.items():
        files = [out_dir / job["output"] for job in jobs]
        have = [f for f in files if f.exists() or state.get(jobs[files.index(f)]["job_id"]).get("status") == "done"]
        if len(have) != len(files):
            lines.append(f"# {variant}: skipped, {len(files) - len(have)} clip(s) not rendered yet")
            continue
        listing = f"final/{variant}.txt"
        lines.append(f"cat > {listing} <<'LIST'")
        lines += [f"file {shlex.quote(str(f.relative_to(out_dir)))}" for f in files]
        lines.append("LIST")
        lines.append(
            f"ffmpeg -y -f concat -safe 0 -i {listing} -c:v libx264 -pix_fmt yuv420p -r 30 final/{variant}.mp4"
        )
        lines.append("")
        written += 1
    path = out_dir / "assemble.sh"
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)
    return path, written


def cmd_check(config, argv):
    cfg = config[PROVIDER]
    if not cfg.get("enabled"):
        log("superscale: disabled in providers.json (using hand-off files + assemble.sh)")
        return 0
    missing = [k for k in ("base_url",) if not cfg.get(k)] + [
        f"paths.{k}" for k in ("submit", "query") if not cfg["paths"].get(k)
    ]
    if missing:
        die("superscale is enabled but not configured: missing " + ", ".join(missing))
    headers_for(cfg, PROVIDER)
    log(f"superscale: enabled, base_url {cfg['base_url']}, credentials present")
    return 0


def cmd_push(config, argv):
    if not argv:
        die("usage: superscale.py push out/<slug>/manifest.json")
    manifest_path = Path(argv[0])
    if not manifest_path.exists():
        die(f"manifest not found: {manifest_path}")
    only = []
    rest = argv[1:]
    while rest:
        flag = rest.pop(0)
        if flag == "--only":
            only.append(rest.pop(0) if rest else die("--only needs a variant id"))
        else:
            die(f"unknown flag: {flag}")

    manifest = json.loads(manifest_path.read_text())
    out_dir = manifest_path.parent
    state = State(out_dir / ".state.json")
    grouped = variants_from(manifest)
    if only:
        grouped = {k: v for k, v in grouped.items() if k in only}
    if not grouped:
        die("no variants matched")

    cfg = config[PROVIDER]
    if not cfg.get("enabled"):
        path, count = write_assemble_script(out_dir, grouped, state)
        log("superscale is disabled in providers.json, so nothing was uploaded.")
        log(f"wrote {path} ({count} variant(s) ready to concat locally)")
        log("")
        log("Per-variant hand-off for the Superscale UI:")
        for variant in grouped:
            log(f"  {out_dir / 'prompts' / variant / 'superscale.json'}")
        log("")
        log("Enable the API instead: fill base_url + paths in pipeline/providers.json,")
        log("set enabled true, export the key, then re-run this command.")
        return 0

    cmd_check(config, [])
    headers = headers_for(cfg, PROVIDER)
    submit_url = cfg["base_url"].rstrip("/") + cfg["paths"]["submit"]
    query_url = cfg["base_url"].rstrip("/") + cfg["paths"]["query"]
    failures = 0

    for variant, jobs in grouped.items():
        job_id = f"superscale/{variant}"
        entry = state.get(job_id)
        if entry.get("status") == "done":
            log(f"skip {variant}: already finished ({entry.get('file', entry.get('url'))})")
            continue

        urls = clip_urls(state, jobs)
        if not urls:
            log(f"skip {variant}: clips not rendered yet - run topview.py render first")
            continue

        handoff = json.loads((out_dir / "prompts" / variant / "superscale.json").read_text())
        payload = {**handoff, "clips": urls, **(cfg.get("extra_payload") or {})}

        task_id = entry.get("task_id")
        if not task_id:
            status, body = request_json("POST", submit_url, headers, payload)
            if status >= 400:
                log(f"FAIL {variant}: submit {status}: {json.dumps(body)[:300]}")
                state.update(job_id, status="failed", error=f"submit {status}")
                failures += 1
                continue
            task_id = dig(body, cfg["task_id_keys"])
            if not task_id:
                log(f"FAIL {variant}: no task id in response: {json.dumps(body)[:300]}")
                state.update(job_id, status="failed", error="no task id")
                failures += 1
                continue
            task_id = str(task_id)
            state.update(job_id, task_id=task_id, status="running")
        log(f"submit {variant} -> {task_id}")

        deadline = time.time() + cfg["poll_timeout_seconds"]
        while True:
            time.sleep(cfg["poll_interval_seconds"])
            status, body = request_json("GET", f"{query_url}?id={task_id}", headers)
            if status >= 400 or not isinstance(body, dict):
                status, body = request_json("POST", query_url, headers, {"id": task_id})
            if status >= 400:
                log(f"warn {variant}: query {status}")
                if time.time() > deadline:
                    break
                continue
            verdict = classify(dig(body, cfg["status_keys"]), cfg)
            if verdict == "running":
                if time.time() > deadline:
                    log(f"FAIL {variant}: timed out (task {task_id} kept in .state.json)")
                    failures += 1
                    break
                continue
            if verdict == "failed":
                msg = str(dig(body, ["error", "message", "errorMsg"]) or "unknown error")
                log(f"FAIL {variant}: {msg}")
                state.update(job_id, status="failed", error=msg)
                failures += 1
                break
            media = find_media_urls(body)
            if not media:
                log(f"FAIL {variant}: finished with no asset url")
                state.update(job_id, status="failed", error="no asset url")
                failures += 1
                break
            dest = out_dir / "final" / f"{variant}.mp4"
            download(media[0], dest)
            log(f"done {variant} -> {dest}")
            state.update(job_id, status="done", url=media[0], file=str(dest))
            break

    return 1 if failures else 0


COMMANDS = {"check": cmd_check, "push": cmd_push}


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__.strip())
        return 0
    command, rest = argv[0], list(argv[1:])
    if command not in COMMANDS:
        die(f"unknown command '{command}' - one of: {', '.join(COMMANDS)}")
    config_path = None
    if "--config" in rest:
        i = rest.index("--config")
        config_path = rest[i + 1] if i + 1 < len(rest) else die("--config needs a path")
        del rest[i : i + 2]
    load_env_file()
    return COMMANDS[command](load_config(config_path), rest)


if __name__ == "__main__":
    run_cli(main)
