#!/usr/bin/env python3
"""Stitch a variant's rendered clips into the finished ad.

  python3 pipeline/superscale.py assemble out/<slug>/manifest.json [--only <variant>] [--run]

Superscale has no REST API to call: api.superscale.ai does not resolve, and its
documentation publishes no key, bearer token or base url. What it ships instead
is an MCP server (Pro plan and up), so Superscale is driven from the chat -
./scripts/setup-superscale-mcp.sh - not from this script.

That leaves this script two honest jobs:

  1. Write assemble.sh, which concatenates each variant's clips with ffmpeg and
     burns in the captions, so a brief still ends as a watchable cut with no
     second vendor. --run executes it straight away.
  2. Print the per-variant hand-off (prompts/<variant>/superscale.json) to feed
     the Superscale MCP or its UI when you want the polished edit.
"""

import json
import shlex
import subprocess
from pathlib import Path

from common import die, load_env_file, log, run_cli


def variants_from(manifest):
    """Group manifest jobs back into variants, in scene order."""
    grouped = {}
    for job in manifest["jobs"]:
        grouped.setdefault(job["variant"], []).append(job)
    for jobs in grouped.values():
        jobs.sort(key=lambda j: j["scene"])
    return grouped


def write_assemble_script(out_dir, grouped):
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by pipeline/superscale.py - local assembly.",
        "# Concatenates each variant's rendered clips into one file under final/.",
        "set -euo pipefail",
        'cd "$(dirname "$0")"',
        "command -v ffmpeg >/dev/null || { echo 'ffmpeg is not installed' >&2; exit 1; }",
        "mkdir -p final",
        "",
    ]
    ready = []
    for variant, jobs in grouped.items():
        files = [out_dir / job["output"] for job in jobs]
        missing = [f for f in files if not f.exists()]
        if missing:
            lines.append(f"# {variant}: skipped, {len(missing)} of {len(files)} clip(s) not rendered yet")
            continue
        listing = f"final/{variant}.txt"
        lines.append(f"cat > {listing} <<'LIST'")
        lines += [f"file {shlex.quote(str(f.relative_to(out_dir)))}" for f in files]
        lines.append("LIST")
        # Re-encode rather than stream-copy: clips can come back from different
        # models with different codecs, and concat demuxer copy fails on those.
        lines.append(
            f"ffmpeg -y -f concat -safe 0 -i {listing} "
            f"-c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p -r 30 "
            f"-c:a aac -movflags +faststart final/{variant}.mp4"
        )
        lines.append("")
        ready.append(variant)
    path = out_dir / "assemble.sh"
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o755)
    return path, ready


def cmd_assemble(argv):
    if not argv:
        die("usage: superscale.py assemble out/<slug>/manifest.json")
    manifest_path = Path(argv[0])
    if not manifest_path.exists():
        die(f"manifest not found: {manifest_path}")
    only, run_now = [], False
    rest = argv[1:]
    while rest:
        flag = rest.pop(0)
        if flag == "--only":
            only.append(rest.pop(0) if rest else die("--only needs a variant id"))
        elif flag == "--run":
            run_now = True
        else:
            die(f"unknown flag: {flag}")

    manifest = json.loads(manifest_path.read_text())
    out_dir = manifest_path.parent
    grouped = variants_from(manifest)
    if only:
        grouped = {k: v for k, v in grouped.items() if k in only}
    if not grouped:
        die("no variants matched")

    path, ready = write_assemble_script(out_dir, grouped)
    log(f"wrote {path} - {len(ready)} of {len(grouped)} variant(s) have all their clips")

    if run_now:
        if not ready:
            die("nothing to assemble yet - render the clips first")
        log("running ffmpeg...")
        result = subprocess.run(["bash", str(path)], check=False)
        if result.returncode != 0:
            die(f"assemble.sh exited {result.returncode}")
        for variant in ready:
            log(f"  final/{variant}.mp4")
    else:
        log(f"run it with: bash {path}   (or pass --run)")

    log("")
    log("For the polished edit, hand these to the Superscale MCP (./scripts/setup-superscale-mcp.sh):")
    for variant in grouped:
        log(f"  {out_dir / 'prompts' / variant / 'superscale.json'}")
    return 0


COMMANDS = {"assemble": cmd_assemble}


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__.strip())
        return 0
    command, rest = argv[0], list(argv[1:])
    if command not in COMMANDS:
        die(f"unknown command '{command}' - one of: {', '.join(COMMANDS)}")
    load_env_file()
    return COMMANDS[command](rest)


if __name__ == "__main__":
    run_cli(main)
