#!/usr/bin/env bash
# Concatenate the source layers into a single drop-in stylesheet.
# No dependencies — the sources are plain CSS, the bundle just saves a request
# (and gives GemPages a single block to paste into custom CSS).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/dist/cupertino.css"
mkdir -p "$here/dist"

{
  printf '/*!\n'
  printf ' * Cupertino DS — bundled stylesheet\n'
  printf ' * Generated by design-system/build.sh — edit design-system/src/*.css instead.\n'
  printf ' */\n'
  for layer in tokens base components; do
    printf '\n'
    cat "$here/src/$layer.css"
  done
} > "$out"

printf 'Built %s (%s lines, %s)\n' \
  "${out#"$here/"}" "$(wc -l < "$out" | tr -d ' ')" \
  "$(wc -c < "$out" | tr -d ' ') bytes"
